modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "extrartp"
version = "${project_version}"
displayName = "${project_name}"
logoFile = "logo.png"
authors = "Vecoo"
description = "Mod adds system of random teleportation the worlds."

[[dependencies.extrartp]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrartp]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ey]]
modId = "extralib"
type = "required"
versionRange = "[2.1.4,)"
ordering = "NONE"
side = "BOTH"