modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "extrartp"
version = "${project_version}"
displayName = "${project_name}"
logoFile = "logo.png"
authors = "Vecoo"
description = "Mod adds system of random teleportation the worlds."

[[dependencies.extrartp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrartp]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrartp]]
modId = "extralib"
mandatory = true
versionRange = "[2.1.4,)"
ordering = "NONE"
side = "BOTH"